### ISSUE TITLE
what license

### ISSUE THREAD

**Issue by zerog2k** [homez/clock-3118AY#1]
hello,
what license do you release this under?
MIT, etc?
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by homez** [comment]
hello,
released under Public Domain (code provided "as is", without warranty of any kind)

**Comment by zerog2k** [comment]
Thanks! 
I'm working on a fork with SDCC (instead of Keil C) support.
